# EDA

## Imports

In [379]:
import pandas as pd

## Process Analysis

In [380]:
df= pd.read_csv('./xmass-hack-2024.csv',encoding='utf8')

In [381]:
df.sample(3)

,ИНН,Дата регистрации,Уставной капитал (руб),Адрес,ФИО Генерального директора,Дата рождения Генерального директора,ФИО Бенефициара,Основной ОКВЭД,Кол-во дополнительных ОКВЭДОВ,Кол-во сотрудников,...,"Доходы (тыс, руб.)",ЗСК,Негативная информация,Негатив относительно ГД,Мошенники,Сервисы регистраторы,Срок жизни SIM-карты/номера (от даты замены e/SIM-карты),Срок жизни SIM в текущем пользовательском устройстве,"Срок жизни SIM-карты/номера (количество дней/часов/минут, которое прошло от даты заключения договора)",Налоговая нагрузка
113623,8601064525,2/19/2024,"10 000,00","Ханты-Мансийский Автономный Округ - Югра, г.о....",NaN,NaN,NaN,86.10,3.0,1.0,...,"5 704,00",NaN,Имеется,NaN,NaN,NaN,NaN,NaN,NaN,-
53879,616206440129,12/9/2021,NaN,г. Ростов-на-Дону,Неволаева Раиса Викторовна,8/13/1993,NaN,69.20,5.0,NaN,...,NaN,NaN,NaN,NaN,"0,09847317731",0.85289,0.0,0.0,0.0,"384 000,00"
112903,7447313609,9/4/2024,"10 000,00",г. Челябинск,NaN,NaN,NaN,41.20,17.0,1.0,...,"1 051,00",2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-

### Rename columns

In [382]:
df= df.rename(
    columns={
        'ИНН': 'inn',
        'Дата регистрации': 'reg_dt',
        ' Уставной капитал (руб)': 'stock_size',
        'Адрес': 'address',
        'ФИО Генерального директора': 'ceo_fn',
        'Дата рождения Генерального директора': 'ceo_bdt',
        'ФИО Бенефициара': 'beneficiary_fn',
        'Основной ОКВЭД': 'prim_okved',
        'Кол-во дополнительных ОКВЭДОВ': 'okved_count',
        'Кол-во сотрудников': 'employee_count',
        'Сайт': 'website',
        'Номер телефона': 'phone_number',
        'Провайдер': 'phone_operator',
        'Система налогообложения ': 'taxation_system',
        'Деятельность клиента': 'client_activity_checked',
        'Деятельность клиента со слов клиента': 'client_activity_verb',
        'Кол-во сотрудников со слов клиента': 'employee_count_verb',
        ' Планируемый оборот по анкете (руб)': 'planned_income_verb',
        ' Планируемый оборот по снятию д/с (руб)': 'planned_withdrawal_verb',
        ' Доходы (тыс, руб.)': 'income',
        'ЗСК': 'zsk',
        'Негативная информация': 'is_negative_info',
        'Негатив относительно ГД': 'is_negative_ceo_info',
        'Мошенники': 'is_fraudelent',
        'Сервисы регистраторы': 'reg_services',
        ' Срок жизни SIM-карты/номера (от даты замены e/SIM-карты)': 'sim_card_lifetime_since_change',
        'Срок жизни SIM в текущем пользовательском устройстве': 'sim_lifetime_in_current_device',
        'Срок жизни SIM-карты/номера (количество дней/часов/минут, которое прошло от даты заключения договора)': 'sim_card_lifetime_since_contract',
        'Налоговая нагрузка': 'tax_burden'
    }
)

### Fill NA

In [383]:
def remove_anomaly(x):
    x = x.str.replace(r'\xa0', '', regex=True).str.strip()
    x = x.str.replace(',', '.', regex=False).str.replace('-', '0', regex=False)     
    
    return x
    

    
df['stock_size']= remove_anomaly(df['stock_size'])
df['stock_size']= df['stock_size'].fillna('0.0')

df['address']= df['address'].fillna('')
df['ceo_fn']= df['ceo_fn'].fillna('')
df['ceo_bdt']= df['ceo_bdt'].fillna('1/1/1900')
df['beneficiary_fn']= df['beneficiary_fn'].fillna('')
df['prim_okved']= df['prim_okved'].fillna('0.00')
df['okved_count']= df['okved_count'].fillna(-1)
df['employee_count']= df['employee_count'].fillna(-1)
df['website']= df['website'].fillna('')

df['phone_number']= df['phone_number'].fillna('')
df['phone_number'] = df['phone_number'].astype(str).str.replace(r'\.0$', '', regex=True)

df['phone_operator']= df['phone_operator'].fillna('')
df['taxation_system']= df['taxation_system'].fillna('')
df['client_activity_checked']= df['client_activity_checked'].fillna('')
df['client_activity_verb']= df['client_activity_verb'].fillna('')
df['employee_count_verb']= df['employee_count_verb'].fillna(-1)

df['planned_income_verb']= remove_anomaly(df['planned_income_verb'])
df['planned_income_verb']= df['planned_income_verb'].fillna('0.0')

df['planned_withdrawal_verb']= remove_anomaly(df['planned_withdrawal_verb'])
df['planned_withdrawal_verb']= df['planned_withdrawal_verb'].fillna('0.0')

df['income']= remove_anomaly(df['income'])
df['income']= df['income'].fillna('0.0')

df['zsk']= df['zsk'].fillna(-1)
df['is_negative_info']= df['is_negative_info'].fillna(0)
df['is_negative_ceo_info']= df['is_negative_ceo_info'].fillna(0)
df['is_fraudelent']= df['is_fraudelent'].fillna(0)
df['reg_services']= df['reg_services'].fillna(-1)
df['sim_card_lifetime_since_change']= df['sim_card_lifetime_since_change'].fillna('1/1/1900')
df['sim_lifetime_in_current_device']= df['sim_lifetime_in_current_device'].fillna('1/1/1900')
df['sim_card_lifetime_since_contract']= df['sim_card_lifetime_since_contract'].fillna('1/1/1900')

df['tax_burden']= df['income']= remove_anomaly(df['tax_burden'])
df['tax_burden']= df['tax_burden'].fillna(0.0)

In [384]:
df['phone_number']

0         79156265755
1         79637277277
2         79872457647
3         79853630115
4         79801430956
             ...
127464    79966292191
127465    79831360899
127466    79996770253
127467    79064146844
127468    79814486475
Name: phone_number, Length: 127469, dtype: object

### Fix types

In [385]:
df['inn']= df['inn'].astype('object')

df['reg_dt']= pd.to_datetime(df['reg_dt'], errors='coerce')
#df['reg_dt'] = df['reg_dt'].fillna(pd.Timestamp('9999-09-09'))

df['stock_size']= df['stock_size'].astype('float64')

df['ceo_bdt']= pd.to_datetime(df['ceo_bdt'], errors='coerce')
#df['ceo_bdt'] = df['ceo_bdt'].fillna(pd.Timestamp('9999-09-09'))

df['okved_count']= df['okved_count'].astype('int')
df['employee_count']= df['employee_count'].astype('int')
df['employee_count_verb']= df['employee_count_verb'].astype('int')
df['planned_income_verb']= df['planned_income_verb'].astype('float64')
df['phone_number']= df['phone_number'].astype('object')
df['planned_withdrawal_verb']= df['planned_withdrawal_verb'].astype('float64')
df['income']= df['income'].astype('float64')
df['zsk']= df['zsk'].astype('int')

df['is_negative_info']= df['is_negative_info'].apply(lambda x: 1 if x=='Имеется' else 0)
df['is_negative_info']= df['is_negative_info'].astype('int')

df['is_negative_ceo_info']= df['is_negative_ceo_info'].apply(lambda x: 1 if x=='Имеется' else 0)
df['is_negative_ceo_info']= df['is_negative_ceo_info'].astype('int')

df['is_fraudelent']= df['is_fraudelent'].apply(lambda x: 1 if x=='Имеется' else 0)
df['is_fraudelent']= df['is_fraudelent'].astype('int')

df['reg_services']= df['reg_services'].astype('float64')

df['sim_card_lifetime_since_change']= pd.to_datetime(df['sim_card_lifetime_since_change'], errors='coerce')
df['sim_card_lifetime_since_change'] = df['sim_card_lifetime_since_change'].fillna(pd.Timestamp('1900-1-1'))

df['sim_lifetime_in_current_device']= pd.to_datetime(df['sim_lifetime_in_current_device'], errors='coerce')
df['sim_lifetime_in_current_device'] = df['sim_lifetime_in_current_device'].fillna(pd.Timestamp('1900-1-1'))

df['sim_card_lifetime_since_contract']= pd.to_datetime(df['sim_card_lifetime_since_contract'], errors='coerce')
df['sim_card_lifetime_since_contract'] = df['sim_card_lifetime_since_contract'].fillna(pd.Timestamp('1900-1-1'))

df['tax_burden']= df['tax_burden'].astype('float64')

In [386]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127469 entries, 0 to 127468
Data columns (total 29 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   inn                               127469 non-null  object
 1   reg_dt                            127469 non-null  datetime64[ns]
 2   stock_size                        127469 non-null  float64
 3   address                           127469 non-null  object
 4   ceo_fn                            127469 non-null  object
 5   ceo_bdt                           127467 non-null  datetime64[ns]
 6   beneficiary_fn                    127469 non-null  object
 7   prim_okved                        127469 non-null  object
 8   okved_count                       127469 non-null  int64
 9   employee_count                    127469 non-null  int64
 10  website                           127469 non-null  object
 11  phone_number                      127469 non-null  object
 12  phone_operator                    127469 non-null  object
 13  taxation_system                   127469 non-null  object
 14  client_activity_checked           127469 non-null  object
 15  client_activity_verb              127469 non-null  object
 16  employee_count_verb               127469 non-null  int64
 17  planned_income_verb               127469 non-null  float64
 18  planned_withdrawal_verb           127469 non-null  float64
 19  income                            127469 non-null  float64
 20  zsk                               127469 non-null  int64
 21  is_negative_info                  127469 non-null  int64
 22  is_negative_ceo_info              127469 non-null  int64
 23  is_fraudelent                     127469 non-null  int64
 24  reg_services                      127469 non-null  float64
 25  sim_card_lifetime_since_change    127469 non-null  datetime64[ns]
 26  sim_lifetime_in_current_device    127469 non-null  datetime64[ns]
 27  sim_card_lifetime_since_contract  127469 non-null  datetime64[ns]
 28  tax_burden                        127469 non-null  float64
dtypes: datetime64[ns](5), float64(6), int64(7), object(11)
memory usage: 28.2+ MB

In [387]:
def analyze_inn(inn):
    if not isinstance(inn, str):
        return 0 # Incorrect  
    
    inn = inn.strip()
    
    if len(inn) == 10:
        return 1 # Company
    elif len(inn) == 12:
        return 2 # Physical 
    else:
        return 0 # Incorrect
        
df['inn'] = df['inn'].astype(str)        
df['inn_type'] = df['inn'].apply(analyze_inn)

In [388]:
def categorize_registration_date(rd):
   
    if pd.isna(rd):
        return 'error'

    today = datetime.today()
    delta = today - rd

    if delta.days < 365:
        return 'new'
    elif 365 <= delta.days < 1095:
        return 'mid'
    else:
        return 'old'

# Пример применения к столбцу DataFrame
df['company_age'] = df['reg_dt'].apply(categorize_registration_date)

In [389]:
def remove_last_four_digits(phone_number):    
    if pd.isna(phone_number):
        return phone_number      
    
    phone_number = str(phone_number).strip()
    return phone_number[:-4] if len(phone_number) > 4 else ''

df['phone_mask'] = df['phone_number'].apply(remove_last_four_digits)

In [390]:
columns_to_merge = [
    'is_negative_info', 
    'is_negative_ceo_info', 
    'is_fraudelent', 
    'reg_services'
]

df['reg_services'] = df['reg_services'].apply(lambda x: 1 if x > 0.5 else 0)
df['is_fraud'] = df[columns_to_merge].max(axis=1)

### Drop

In [391]:
df.head()

,inn,reg_dt,stock_size,address,ceo_fn,ceo_bdt,beneficiary_fn,prim_okved,okved_count,employee_count,...,is_fraudelent,reg_services,sim_card_lifetime_since_change,sim_lifetime_in_current_device,sim_card_lifetime_since_contract,tax_burden,inn_type,company_age,phone_mask,is_fraud
0,620500012412,2022-08-12,0.0,,,1900-01-01,,47.11,8,-1,...,0,0,1900-01-01,1900-01-01,1900-01-01,0.0,2,mid,7915626,0
1,470307531695,2021-04-15,0.0,г. Москва,Чадин Сергей Вячеславович,1979-02-11,,70.22,21,-1,...,0,0,1900-01-01,1900-01-01,1900-01-01,1920000.0,2,old,7963727,1
2,27362587579,2023-03-16,0.0,г. Уфа,Ибраев Муйтен Ирекович,2003-07-02,,43.99,1,-1,...,0,1,1900-01-01,1900-01-01,1900-01-01,384000.0,0,mid,7987245,1
3,773571821385,2022-08-11,0.0,,,1900-01-01,,47.19,5,-1,...,0,0,1900-01-01,1900-01-01,1900-01-01,0.0,2,mid,7985363,0
4,300114774045,2022-04-18,0.0,Астраханская область,Бондаренко Вячеслав Александрович,1978-06-20,,46.90,14,-1,...,0,0,1900-01-01,1900-01-01,1900-01-01,384000.0,2,mid,7980143,0

In [392]:
df_ml= df.drop(
    columns=[
        'inn', # we want to remove this column or else our model will be overfitted
        'reg_dt', # we want to remove this column or else our model will be overfitted
        'stock_size', # same as above- hight risk of overfitting. Also it is hard to categorize it as dasta is bad
        'address', # Overfitting risk
        'ceo_fn', # overfitting
        'beneficiary_fn', # overfitting
        'okved_count', # overfitting
        'employee_count', # overfitting    
        'phone_operator', # overfitting
        'client_activity_checked', # overfitting
        'client_activity_verb', # not relieble
        'employee_count_verb', # not relieble
        'planned_income_verb', # not relieble
        'planned_withdrawal_verb', # not relieble
        'sim_card_lifetime_since_change', # good info but useleess as we don't have tool to get this info
        'sim_lifetime_in_current_device', # good info but useleess as we don't have tool to get this info
        'sim_card_lifetime_since_contract', # good info but useleess as we don't have tool to get this info
        'tax_burden', # overfitting and bad data
        'taxation_system', # good info but we can't get that info for free
        'ceo_bdt', # good info but we can't get that info for free
        'website', # untrusted source
        'phone_number', # this could lead to overfitting, insted we will use phone without last 4 digits
        'is_negative_info', # this and below has been merged into one column
        'is_negative_ceo_info', 
        'is_fraudelent',
        'reg_services',
        'income' # not relieble source for trainig
    ]
)

In [396]:
df_ml = df_ml.loc[df_ml['inn_type'] > 0]

In [405]:
df_ml.sample(5)

      prim_okved  zsk  inn_type company_age phone_mask  is_fraud
75839      41.20    1         1         mid    7930270         1
15535      82.30   -1         1         mid    7926061         1
89386      46.13    2         1         mid    7912872         1
88398      46.90    1         1         mid    7923129         0
20037      43.22   -1         2         mid    7999980         0

In [288]:
df_ml.shape

(127469, 12)

In [402]:
len(df_ml.loc[df_ml['inn_type']==0])

0

In [404]:
len(df.loc[df['prim_okved']==0.0])

0

In [406]:
df_ml.to_csv('ds_final.csv')